### PR TITLE
Added new restart server feature & readme update + other updates 

### PR DESCRIPTION
**Pull request by Pringlez**
Updated the installation guides on both Linux + Windows machines
Added restart feature to ac server + sTracker
Updated tyres selection
New UI layout
Improved HTML format / clean up code

### CODE REVIEW

**Comment by surtic86** [comment]
@jo3stevens time to merge?

**Comment by jo3stevens** [comment]
For some reason I missed this. I've not been active on the project for a while but was planning to update it all soon for latest settings. Will have a look at the changes here.

Cheers

**Comment by jo3stevens** [comment]
Hey @Pringlez and @surtic86 

What was the basic auth issue? Was in linux specific? It's always worked for me on windows.

Thanks

**Comment by jo3stevens** [comment]
@Pringlez @surtic86 

All merged, like the design change!

Cheers

**Comment by surtic86** [comment]
@jo3stevens The basic auth Problem was coming with the Update on Express JS. It was just needed to get the new Basic Auth package.

**Pull request merged**
